title: ELIXIR Data Steward Handbook
# this appears in the html browser tab for the site title (seen mostly by search engines, not users)

description: ""
# Metadata description of the website

remote_theme: ELIXIR-Belgium/elixir-toolkit-theme

topnav_title: Data Steward Handbook

theme_variables:
  topnav:
    brand_logo: assets/img/main_logo.svg

sass:
  style: compressed
  sourcemap: never

gtag: 
# Google analytics tag

# dsw_deep_link_prefix: https://researchers.ds-wizard.org/knowledge-models/dsw:root:latest/preview?questionUuid=
# prefix for DSW deep links to a certain question


exclude:
  - README.md

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      permalink: /:basename
      layout: "page"
      search_exclude: false
  -
    scope:
      path: "pages/about"
    values:
      sidebar: about
  -
    scope:
      path: "pages/case-studies"
    values:
      sidebar: case-studies
  -
    scope:
      path: "pages/case-studies/case-studies-uk"
    values:
      type: UK
  -
    scope:
      path: "pages/case-studies/case-studies-nl"
    values:
      type: NL
  -
    scope:
      path: "pages/case-studies/case-studies-fi"
    values:
      type: FI
  -
    scope:
      path: "pages/guidelines"
    values:
      sidebar: guidelines
  -
    scope:
      path: "pages/guidelines/guidelines-support"
    values:
     type: Guidelines_Support
  -
    scope:
      path: "pages/guidelines/guidelines-legal"
    values:
     type: Guidelines_Legal
  -
    scope:
      path: "pages/guidelines/guidelines-rdm-strategy"
    values:
     type: Guidelines_RDM_Strategy
  -
    scope:
      path: "pages/maturity-model"
    values:
      sidebar: maturity-model
  -
    scope:
      path: "pages/maturity-model/mm-strategy"
    values:
      type: Maturity_Model_Strategy
  -
    scope:
      path: "pages/maturity-model/mm-legal"
    values:
      type: Maturity_Model_Legal
  -
    scope:
      path: "pages/maturity-model/mm-data"
    values:
      type: Maturity_Model_Data
  -
    scope:
      path: "pages/maturity-model/mm-support"
    values:
      type: Maturity_Model_Support

scholar:
  style: _bibliography/nature_custom.csl

plugins:
  - elixir-toolkit-theme-plugins
  - jemoji
  - jekyll-redirect-from
  - jekyll-sitemap
  - jekyll-github-metadata
  - jekyll-octicons
  - jekyll-scholar