title: ELIXIR Data Stewardship Handbook
# this appears in the html browser tab for the site title (seen mostly by search engines, not users)

description: ""
# Metadata description of the website

remote_theme: ELIXIR-Belgium/elixir-toolkit-theme

topnav_title: Data Stewardship Handbook

theme_variables:
  topnav:
    brand_logo: assets/img/main_logo.svg

sass:
  style: compressed
  sourcemap: never

gtag: 
# Google analytics tag

# dsw_deep_link_prefix: https://researchers.ds-wizard.org/knowledge-models/dsw:root:latest/preview?questionUuid=
# prefix for DSW deep links to a certain question


exclude:
  - README.md

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      permalink: /:basename
      layout: "page"
      search_exclude: false
  -
    scope:
      path: "pages/about"
    values:
      sidebar: about
  -
    scope:
      path: "pages/case-studies"
    values:
      sidebar: case-studies
      type: case-study
  -
    scope:
      path: "pages/guidance"
    values:
      sidebar: guidance
      type: guidance
  -
    scope:
      path: "pages/maturity-model"
    values:
      sidebar: maturity-model
      type: maturity-model
  -
    scope:
      path: "pages/maturity-model/mm-strategy"
    values:
      type: maturity-model-strategy
  -
    scope:
      path: "pages/maturity-model/mm-legal"
    values:
      type: maturity-model-legal
  -
    scope:
      path: "pages/maturity-model/mm-data"
    values:
      type: maturity-model-data
  -
    scope:
      path: "pages/maturity-model/mm-support"
    values:
      type: maturity-model_support

scholar:
  style: _bibliography/nature_custom.csl

plugins:
  - elixir-toolkit-theme-plugins
  - jemoji
  - jekyll-redirect-from
  - jekyll-sitemap
  - jekyll-github-metadata
  - jekyll-octicons
  - jekyll-scholar
