title: Data Stewardship Handbook
# this appears in the html browser tab for the site title (seen mostly by search engines, not users)

description: ""
# Metadata description of the website

remote_theme: ELIXIR-Belgium/elixir-toolkit-theme


sass:
  style: compressed
  sourcemap: never

theme_variables:
  topnav:
    brand_logo: assets/img/main-logo-right.svg
    theme: dark
  fonts:
    - https://fonts.googleapis.com/css2?family=Caveat:wght@400..700&family=Inter:ital,opsz,wght@0,14..32,100..900;1,14..32,100..900&display=swap

topnav_banner: "The Handbook is currently under development and may change at any point - it is not meant for production use"
# Optional: a banner message to display to users on all pages

gtag: 
# Google analytics tag

# dsw_deep_link_prefix: https://researchers.ds-wizard.org/knowledge-models/dsw:root:latest/preview?questionUuid=
# prefix for DSW deep links to a certain question


exclude:
  - README.md
  - .gitignore
  - var/
  - vendor
  - Gemfile*
  - LICENSE

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      permalink: /:basename
      layout: "page"
      search_exclude: false
  -
    scope:
      path: "pages/about"
    values:
      sidebar: about
  -
    scope:
      path: "pages/case-studies"
    values:
      sidebar: case-studies
  -
    scope:
      path: "pages/guidance"
    values:
      sidebar: guidance
  -
    scope:
      path: "pages/maturity-model"
    values:
      sidebar: maturity-model

scholar:
  style: _bibliography/nature_custom.csl

plugins:
  - elixir-toolkit-theme-plugins
  - jemoji
  - jekyll-redirect-from
  - jekyll-sitemap
  - jekyll-github-metadata
  - jekyll-octicons
  - jekyll-scholar
